### ISSUE TITLE
Delete all

### ISSUE THREAD

**Issue by ealloradai** [asonawalla/FBEraser#16]
Hi
How coul this script modified to completely erase the fb account?

**Comment by asonawalla** [comment]
It's not intended to erase an entire account, only posts.  Sounds like you want to [deactivate your Facebook account](https://www.facebook.com/help/214376678584711)

**Comment by ealloradai** [comment]
no,
i don't want to deactivate account, i want to delete all except friends

2015-09-24 5:08 GMT+02:00 Azim Sonawalla notifications@github.com:

**Comment by asonawalla** [comment]
The current build deletes all of your posts only for the time being.  Facebook offers limited control of how you can remove content that involves you (e.g. posts by friends in which you are tagged), and those controls tend to change.  I would like to eventually include some method of addressing the removal of all that content, but at the moment it's a bit over the horizon.

I'd recommend you start the script and let it run in its current form.  That will remove all your posts.  You can experiment with the [activity link](https://github.com/asonawalla/FBEraser/blob/master/FBEraser.py#L62) (specifically `log_filter=cluster_11`; that is what filters by 'your posts') to see if you can cover more ground on deletion, but my results have been wildly inconsistent.
