### ISSUE TITLE
Mask password input

### ISSUE THREAD

**Issue by asonawalla** [asonawalla/FBEraser#5]
Via reddit /u/sad-king-billy

Use something like getpass so that the password isn't visible as plain text

**Comment by bryceandress** [comment]
I can look into this if you would like. Just learning Python and seems like a fun task

**Comment by asonawalla** [comment]
@bryceandress sounds good man - send me a pull request when you have something!

I'd recommend taking the username and pw out of argparse (remove the arguments) and put a prompt in the `if __name__ == '__main__':` section.

**Comment by bryceandress** [comment]
@asonawalla was actually going to message you and see if that was okay with you. My thoughts exactly

Pull request was submitted
